name: Push blog to server # 名字自取

on:
  push:
    branches:
      - main  # 这里的意思是当 main分支发生push的时候，运行下面的jobs，这里先改为github-actions

jobs:
  deploy: # 任务名自取
    runs-on: ubuntu-20.04	# 在什么环境运行任务
    steps:
      - uses: actions/checkout@v2	# 引用actions/checkout这个action，与所在的github仓库同名
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive) 获取submodule主题
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Upload Website
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzh
          path: "./*"
          remote_path: "/home/ubuntu/Website/Blog/Personal"
          remote_host: "101.42.141.88"
          remote_port: "22"
          remote_user: ubuntu
          remote_key: ${{ secrets.COMFLUTER_KEY}}
          
#      - name: Upload Website
#        uses: zhenyuWang/Upload-File-Action@v1.0.1
#        with:
#          username: "root"
#          server: "110.42.134.69"
#          port: "22"
#          ssh_private_key: ${{ secrets.WEBSITE_ACCESS_TOKEN}}
#          # 要上传文件所在目录
#          local_path: "./public/*"
#          # 远程服务器目标路径
#          target_path: "/www/wwwroot/blog"
